const colors = {
  light: {
    text: "#0A0E1A",
    tint: "#5B7FFF",
    background: "#F4F6FF",
    foreground: "#0A0E1A",
    card: "#FFFFFF",
    cardForeground: "#0A0E1A",
    primary: "#5B7FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2FF",
    secondaryForeground: "#3B4FCC",
    muted: "#EEF2FF",
    mutedForeground: "#6B7280",
    accent: "#FF6B8A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E9FF",
    input: "#E5E9FF",
    success: "#4ADE80",
    warning: "#FBBF24",
    youtube: "#FF0000",
    twitter: "#1D9BF0",
    reddit: "#FF4500",
    rss: "#F97316",
    match: "#FF6B8A",
  },
  dark: {
    text: "#F0F4FF",
    tint: "#5B7FFF",
    background: "#0A0E1A",
    foreground: "#F0F4FF",
    card: "#141929",
    cardForeground: "#F0F4FF",
    primary: "#5B7FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1E2A45",
    secondaryForeground: "#A5B4FC",
    muted: "#1E2A45",
    mutedForeground: "#6B7280",
    accent: "#FF6B8A",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E2A45",
    input: "#1E2A45",
    success: "#4ADE80",
    warning: "#FBBF24",
    youtube: "#FF0000",
    twitter: "#1D9BF0",
    reddit: "#FF4500",
    rss: "#F97316",
    match: "#FF6B8A",
  },
  radius: 14,
};

export default colors;
