kind = "mobile"
previewPath = "/"
title = "KeyP"
version = "1.0.0"
id = "artifacts/keyp"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23101

[services.development]
run = "pnpm --filter @workspace/keyp run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/keyp", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/keyp", "run", "serve" ]

[services.env]
PORT = "23101"
BASE_PATH = "/"
